"""Add download source columns for objects

Revision ID: 0fc13d8a7182
Revises: b838ef3372ca
Create Date: 2026-01-06 15:57:52.651223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc13d8a7182'
down_revision = 'b838ef3372ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_object', sa.Column('post_download_source', sa.String(length=13), nullable=True))
    op.add_column('reddit_object_list', sa.Column('post_download_source', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_object', 'post_download_source')
    op.drop_column('reddit_object_list', 'post_download_source')
    # ### end Alembic commands ###
